version: "3.7"

services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  rusanit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgresdb

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgresdb
      - rusanit
    volumes:
      - ./static/:/static
      - ./docker/nginx/certs:/etc/ssl/certs